### ISSUE TITLE
Notes don't sync at night

### ISSUE THREAD

**Issue by abhishekarora12** [streetwriters/notesnook#2514]
### What happened?

I have been facing this issue from the past few days, when i try syncing the notes on my android phone at night (like 3/4am IST), they don't sync and i get needless note merges

# Screenshot
![WhatsApp Image 2023-05-09 at 11 06 25 PM](https://github.com/streetwriters/notesnook/assets/12087783/05dab7b7-6f86-432b-a7b2-5547f2267fea)

### Steps to reproduce the problem

 Try syncing notes in android at night at 3am indian time on android device 

### Version

2.4.15

### Platform/OS

Android

### Relevant log output

```shell
If I click on copy log in the screenshot, nothing gets copied so i can't put anything here
```

**Comment by abhishekarora12** [comment]
Faced the same issue again yesterday, Is the sync server down for maintenance at night?

Fortunately, this time I was able to get the logs (below)

# Screenshot
![WhatsApp Image 2023-05-10 at 2 57 21 PM](https://github.com/streetwriters/notesnook/assets/12087783/524f2338-0e66-4e6f-9605-b75bc4e5ac32)


# Logs
```
Error: Could not connect to the Sync server. Please try again.
    at ?anon_0_ (address at [index.android](http://index.android/).bundle:1:2318277)
    at throw (native)
    at asyncGeneratorStep (address at [index.android](http://index.android/).bundle:1:3054972)
    at _throw (address at [index.android](http://index.android/).bundle:1:3055289)
    at tryCallOne (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/602d1x6z/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:53:16)
    at anonymous (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/602d1x6z/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:139:27)
    at apply (native)
    at anonymous (address at [index.android](http://index.android/).bundle:1:1107647)
    at _callTimer (address at [index.android](http://index.android/).bundle:1:1106639)
    at _callReactNativeMicrotasksPass (address at [index.android](http://index.android/).bundle:1:1106808)
    at callReactNativeMicrotasks (address at [index.android](http://index.android/).bundle:1:1108729)
    at __callReactNativeMicrotasks (address at [index.android](http://index.android/).bundle:1:1005109)
    at anonymous (address at [index.android](http://index.android/).bundle:1:1004233)
    at __guard (address at [index.android](http://index.android/).bundle:1:1004986)
    at flushedQueue (address at [index.android](http://index.android/).bundle:1:1004144)
    at callFunctionReturnFlushedQueue (address at [index.android](http://index.android/).bundle:1:1004000)
```

**Comment by thecodrr** [comment]
I haven't noticed the sync server going down in the past 3-4 months and we haven't done any maintenance recently. It is possible that the hosting service we are using goes down for maintenance but no other user has reported anything of the sort.

Are you still having this issue?

**Comment by abhishekarora12** [comment]
I had to reinstall the app since even update didn't fix it but I am not getting it now.
