### ISSUE TITLE
Sync Failure

### ISSUE THREAD

**Issue by userkace** [streetwriters/notesnook#3189]
Error: FAILURE
    at promiseMethodWrapper (address at index.android.bundle:1:1345660)
    at ?anon_0_ (address at index.android.bundle:1:1867187)
    at next (native)
    at asyncGeneratorStep (address at index.android.bundle:1:3301584)
    at _next (address at index.android.bundle:1:3301854)
    at anonymous (address at index.android.bundle:1:3301806)
    at tryCallTwo (/root/react-native/packages/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5u5c1a82/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:61:9)
    at doResolve (/root/react-native/packages/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5u5c1a82/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:216:25)
    at Promise (/root/react-native/packages/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5u5c1a82/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:82:14)
    at anonymous (address at index.android.bundle:1:3301727)
    at apply (native)
    at decrypt (address at index.android.bundle:1:1866995)
    at decrypt (address at index.android.bundle:1:2719452)
    at ?anon_0_ (address at index.android.bundle:1:2634735)
    at next (native)
    at asyncGeneratorStep (address at index.android.bundle:1:3389438)
    at _next (address at index.android.bundle:1:3389708)
    at anonymous (address at index.android.bundle:1:3389660)
    at tryCallTwo (/root/react-native/packages/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5u5c1a82/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:61:9)
    at doResolve (/root/react-native/packages/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5u5c1a82/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:216:25)
    at Promise (/root/react-native/packages/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5u5c1a82/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:82:14)
    at anonymous (address at index.android.bundle:1:3389581)
    at apply (native)
    at _deserialize (address at index.android.bundle:1:2634649)
    at ?anon_0_ (address at index.android.bundle:1:2634957)
    at next (native)
    at asyncGeneratorStep (address at index.android.bundle:1:3389438)
    at _next (address at index.android.bundle:1:3389708)
    at anonymous (address at index.android.bundle:1:3389660)
    at tryCallTwo (/root/react-native/packages/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5u5c1a82/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:61:9)
    at doResolve (/root/react-native/packages/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5u5c1a82/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:216:25)
    at Promise (/root/react-native/packages/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5u5c1a82/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:82:14)
    at anonymous (address at index.android.bundle:1:3389581)
    at apply (native)
    at _mergeItem (address at index.android.bundle:1:2634922)
    at ?anon_0_ (address at index.android.bundle:1:2635918)
    at next (native)
    at asyncGeneratorStep (address at index.android.bundle:1:3389438)
    at _next (address at index.android.bundle:1:3389708)
    at tryCallOne (/root/react-native/packages/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5u5c1a82/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:53:16)
    at anonymous (/root/react-native/packages/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5u5c1a82/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:139:27)
    at apply (native)
    at anonymous (address at index.android.bundle:1:1446317)
    at _callTimer (address at index.android.bundle:1:1445309)
    at _callReactNativeMicrotasksPass (address at index.android.bundle:1:1445478)
    at callReactNativeMicrotasks (address at index.android.bundle:1:1447392)
    at __callReactNativeMicrotasks (address at index.android.bundle:1:1343737)
    at anonymous (address at index.android.bundle:1:1342863)
    at __guard (address at index.android.bundle:1:1343614)
    at flushedQueue (address at index.android.bundle:1:1342774)
    at callFunctionReturnFlushedQueue (address at index.android.bundle:1:1342630)

**Comment by userkace** [comment]
Multiple instance of the same account trying to sync. I reconnected all my devices and it worked.

There was an issue where one of the devices was still using an older password which was causing the issue.
