### ISSUE TITLE
Sync failed with "Merge conflicts detected. Please resolve all conflicts to continue syncing."

### ISSUE THREAD

**Issue by muchqs** [streetwriters/notesnook#3410]
### What happened?

Android 9.
Upgraded to v2.6.5.
When syncing it says "Merge conflicts detected. Please resolve all conflicts to continue syncing."
"Force Sync" in options give the same error.
I force stopped the app. Cleared cache and data. Relog into the app. It synced fine with no error.
Next day I start the app, same error showed up again. Cleared cache and data. Error gone again...
There is only one option given, "Copy Log"
So here is the log attached.

### Steps to reproduce the problem

1. start app
2. sync fails

### Version

2.6.5

### Platform/OS

Android

### Relevant log output

```shell
Error: Merge conflicts detected. Please resolve all conflicts to continue syncing.
    at _throw (address at index.android.bundle:1:2631492)
    at ?anon_0_ (address at index.android.bundle:1:2637145)
    at next (native)
    at fulfilled (address at index.android.bundle:1:2633011)
    at tryCallOne (/root/react-native/packages/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5u5c1a82/armeabi-v7a/lib/InternalBytecode/InternalBytecode.js:53:16)
    at anonymous (/root/react-native/packages/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5u5c1a82/armeabi-v7a/lib/InternalBytecode/InternalBytecode.js:139:27)
    at apply (native)
    at anonymous (address at index.android.bundle:1:1438808)
    at _callTimer (address at index.android.bundle:1:1437800)
    at _callReactNativeMicrotasksPass (address at index.android.bundle:1:1437969)
    at callReactNativeMicrotasks (address at index.android.bundle:1:1439883)
    at __callReactNativeMicrotasks (address at index.android.bundle:1:1336222)
    at anonymous (address at index.android.bundle:1:1335348)
    at __guard (address at index.android.bundle:1:1336099)
    at flushedQueue (address at index.android.bundle:1:1335259)
    at callFunctionReturnFlushedQueue (address at index.android.bundle:1:1335115)
```

**Comment by thecodrr** [comment]
@muchqs you should not log out when you see this error. That will result in data loss. Merge conflict means that the local & cloud copies of your note were both edited resulting in the app not knowing which copy to keep. You have to manually resolve these conflicts:

1. Go to the Notes page/tab/view
2. You will see all conflicted notes at the very top of the list (with red exclamation mark)
3. Tap to open a conflict
4. You will see both copies side-by-side
5. Carefully compare both copies and see which one to keep
6. Click "Save" on the copy you want to keep
7. The other copy will show 2 buttons (Save a copy or Discard)
8. Discard means that the other copy will be deleted
9. Save a copy means that the other copy will be saved as a duplicate

Once you have resolved all conflicts, sync will automatically run.
