### ISSUE TITLE
App crashes everytime in background after closing

### ISSUE THREAD

**Issue by NikunjKhangwal** [streetwriters/notesnook#3742]
### What happened?

The app crash itself in background everytime after closing it from recent apps. For re-opening it, i need to click on the icon multiple times (i get multiple auto closing blank windows during this) or wait a few seconds for it to fix itself.

### Steps to reproduce the problem

Looks like its conflicting with Zygote process

### Version

v2.6.8

### Platform/OS

Android

### Relevant log output

```shell
java.lang.UnsatisfiedLinkError: No implementation found for void com.ammarahmed.mmkv.MMKV.jniInitialize(java.lang.String, int) (tried Java_com_ammarahmed_mmkv_MMKV_jniInitialize and Java_com_ammarahmed_mmkv_MMKV_jniInitialize__Ljava_lang_String_2I) - is the library loaded, e.g. System.loadLibrary?
	at com.ammarahmed.mmkv.MMKV.jniInitialize(Native Method)
	at com.ammarahmed.mmkv.MMKV.k(Unknown Source:1)
	at com.ammarahmed.mmkv.MMKV.j(Unknown Source:25)
	at com.streetwriters.notesnook.OnClearFromRecentService.onTaskRemoved(Unknown Source:4)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4810)
	at android.app.ActivityThread.access$2200(ActivityThread.java:275)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2206)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8280)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)
```

**Comment by thecodrr** [comment]
Hey, where did you install the app from? Is this the F-Droid version, GitHub version or Google Play version?

**Comment by ammarahm-ed** [comment]
Hi, what is the phone model and android version where you are seeing this?

**Comment by NikunjKhangwal** [comment]
> Hey, where did you install the app from? Is this the F-Droid version, GitHub version or Google Play version?

It's the Google Play version

**Comment by NikunjKhangwal** [comment]
> Hi, what is the phone model and android version where you are seeing this?

Poco M2, Android 12

**Comment by thecodrr** [comment]
@NikunjKhangwal is it a custom ROM?

**Comment by NikunjKhangwal** [comment]
Hello, just wanted to mentioned this problem isn't occurring after updating to 2.6.9

**Comment by ammarahm-ed** [comment]
> Hello, just wanted to mentioned this problem isn't occurring after updating to 2.6.9

Thanks, yes it has been fixed.
