### ISSUE TITLE
Sqlite error while opening the tags section of the windows app

### ISSUE THREAD

**Issue by Vade86** [streetwriters/notesnook#4646]
### What happened?

When I try to open the tags section of the app, I keep getting an error "something went wrong" and asked to restart the app

### Steps to reproduce the problem

1. Open the Notesnook app
2. Go to the tags section in the sidebar
3. App crashes and requires restart

### Version

3.0.12-7368796-desktop-beta

### Platform/OS

Windows

### Relevant log output

```shell
no such column: dateEdited
SqliteError: no such column: dateEdited
    at Database.prepare (C:\Users\VS\AppData\Local\Programs\@notesnookdesktop\resources\app\node_modules\better-sqlite3-multiple-ciphers\lib\methods\wrappers.js:5:21)
    at iX.executeQuery (https://app.notesnook.com/assets/index-04f35fb1.js:1222:166646)
    at https://app.notesnook.com/assets/index-04f35fb1.js:209:52711
    at hH.provideConnection (https://app.notesnook.com/assets/index-04f35fb1.js:209:95764)
    at async jo.executeQuery (https://app.notesnook.com/assets/index-04f35fb1.js:209:52656)
    at async ve.execute (https://app.notesnook.com/assets/index-04f35fb1.js:209:60437)
```

**Comment by Vade86** [comment]
Similar error using the latest beta version of the Android app. But the app does not crash. Here are the logs:

`Error: [react-native-quick-sqlite] SQL execution error: no such column: dateEdited`


Android app version: 3.0.16
OS: Android 14
