### ISSUE TITLE
No sync 

### ISSUE THREAD

**Issue by PerkelSimon** [streetwriters/notesnook#4797]
### What happened?

There is no sync at all, problems to reach network.

### Steps to reproduce the problem

Just try to sync 😀

### Version

2.6.18

### Platform/OS

Android

### Relevant log output

```shell
Error: Could not connect to the Sync server. Please try again.
    at ?anon_0_ (address at index.android.bundle:1:2631970)
    at throw (native)
    at rejected (address at index.android.bundle:1:2623398)
    at tryCallOne (/root/react-native/packages/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5u5c1a82/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:53:16)
    at anonymous (/root/react-native/packages/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5u5c1a82/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:139:27)
    at apply (native)
    at anonymous (address at index.android.bundle:1:1441601)
    at _callTimer (address at index.android.bundle:1:1440593)
    at _callReactNativeMicrotasksPass (address at index.android.bundle:1:1440762)
    at callReactNativeMicrotasks (address at index.android.bundle:1:1442676)
    at __callReactNativeMicrotasks (address at index.android.bundle:1:1339004)
    at anonymous (address at index.android.bundle:1:1338130)
    at __guard (address at index.android.bundle:1:1338881)
    at flushedQueue (address at index.android.bundle:1:1338041)
    at callFunctionReturnFlushedQueue (address at index.android.bundle:1:1337897
```

**Comment by thecodrr** [comment]
Hi, your error is related to a network error which can be due to you using a VPN/DNS or a firewall blocking the connection to Notesnook servers. If you aren't using a VPN, I also suggest trying again with a VPN.
