### ISSUE TITLE
3.0 - Processing of database failed

### ISSUE THREAD

**Issue by shift18** [streetwriters/notesnook#4885]
### What happened?

App fails to process database (notes) after update.

I close the app and restart it as it has remained frozen for an unreasonable amount of time.
I get error (see log)

I now had to clear app storage to be able to relog

### Steps to reproduce the problem

1. So i installed 3.0 from github
2. I open the app
3. The app need to proccessed the database
4. It start prcoessing notes, It seems to process all my notes ok
5. now it gets stuck on second stage of import, 0/0

### Version

Android 3.0 | Firefox/Windows 3.0.0-583d585-web

### Platform/OS

Android

### Relevant log output

```shell
Error: Please login to create encrypted backups.
    at ?anon_0_ (address at [index.android](http://index.android/).bundle:1:2894676)
    at next (native)
    at resume (address at [index.android](http://index.android/).bundle:1:2892809)
    at fulfill (address at [index.android](http://index.android/).bundle:1:2892988)
    at tryCallOne (/root/react-native/packages/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5u5c1a82/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:53:16)
    at anonymous (/root/react-native/packages/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5u5c1a82/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:139:27)
    at apply (native)
    at anonymous (address at [index.android](http://index.android/).bundle:1:1494626)
    at _callTimer (address at [index.android](http://index.android/).bundle:1:1493618)
    at _callReactNativeMicrotasksPass (address at [index.android](http://index.android/).bundle:1:1493787)
    at callReactNativeMicrotasks (address at [index.android](http://index.android/).bundle:1:1495703)
    at __callReactNativeMicrotasks (address at [index.android](http://index.android/).bundle:1:1391983)
    at anonymous (address at [index.android](http://index.android/).bundle:1:1391109)
    at __guard (address at [index.android](http://index.android/).bundle:1:1391860)
    at flushedQueue (address at [index.android](http://index.android/).bundle:1:1391020)
    at invokeCallbackAndReturnFlushedQueue (address at [index.android](http://index.android/).bundle:1:1390963)
```

**Comment by thecodrr** [comment]
Fix for this is coming in the upcoming version. Sorry for the inconvenience.

**Comment by ammarahm-ed** [comment]
This has been fixed.
