### ISSUE TITLE
Error while scrolling down notes for linking

### ISSUE THREAD

**Issue by mtsbh** [streetwriters/notesnook#4969]
### What happened?

When I scrolled down into my notes to chose one for the bi-directional links and I get to the same part of the notes I receive an error.

### Steps to reproduce the problem

1. Mark some text
2. Click on `add a bi-directional link`
3. Scroll down the list of notes

idk if you will be able to reproduce but happened to me 3 times in 2 minutes so I decide to let you know.

### Version

3.0.0-94b28f8-desktop

### Platform/OS

Windows

### Relevant log output

```shell
Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at mi (https://app.notesnook.com/assets/index-3dcf0efe.js:795:33829)
    at wM (https://app.notesnook.com/assets/index-3dcf0efe.js:793:24418)
    at Object.onChange (https://app.notesnook.com/assets/index-ad95361ef911.js:249:10639)
    at Jte.notify (https://app.notesnook.com/assets/index-ad95361ef911.js:249:2659)
    at Jte.resizeItem (https://app.notesnook.com/assets/index-ad95361ef911.js:249:6733)
    at Jte._measureElement (https://app.notesnook.com/assets/index-ad95361ef911.js:249:6374)
    at Jte.measureElement (https://app.notesnook.com/assets/index-ad95361ef911.js:249:6778)
    at P2 (https://app.notesnook.com/assets/index-3dcf0efe.js:795:24419)
    at s8 (https://app.notesnook.com/assets/index-3dcf0efe.js:795:32557)
    at Ek (https://app.notesnook.com/assets/index-3dcf0efe.js:795:31466)
```
```

**Comment by ammarahm-ed** [comment]
I am unable to reproduce this in the latest version.
