### ISSUE TITLE
Desktop App 3.0.1 on Linux not usable

### ISSUE THREAD

**Issue by ArGei26** [streetwriters/notesnook#5058]
### What happened?

Version 3.0.1 on the Linux Desktop only shows a blank screen.
On the command line ist says
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed (see below)

### Steps to reproduce the problem

start the linux desktop app

### Version

3.0.1

### Platform/OS

Linux

### Relevant log output

```shell
Update for version 3.0.1 is not available (latest version: 3.0.1, downgrade is disallowed).
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at s.send (node:electron/js2c/browser_init:2:84285)
    at _.sendToFrame (node:electron/js2c/browser_init:2:69747)
    at e.reply (node:electron/js2c/browser_init:2:76322)
    at h (/tmp/.mount_notesng9Fd0W/resources/app/build/electron.js:137:12729)
    at Object.next (/tmp/.mount_notesng9Fd0W/resources/app/build/electron.js:137:13055)
    at Object.next (/tmp/.mount_notesng9Fd0W/resources/app/build/electron.js:74:2492)
    at Ch.r (/tmp/.mount_notesng9Fd0W/resources/app/build/electron.js:144:8068)
    at Ch.emit (node:events:514:28)
    at Ch.doCheckForUpdates (/tmp/.mount_notesng9Fd0W/resources/app/build/electron.js:61:12577)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at s.send (node:electron/js2c/browser_init:2:84285)
    at _.sendToFrame (node:electron/js2c/browser_init:2:69747)
    at e.reply (node:electron/js2c/browser_init:2:76322)
    at h (/tmp/.mount_notesng9Fd0W/resources/app/build/electron.js:137:12729)
    at Vq (/tmp/.mount_notesng9Fd0W/resources/app/build/electron.js:137:12866)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at s.send (node:electron/js2c/browser_init:2:84285)
    at _.sendToFrame (node:electron/js2c/browser_init:2:69747)
    at e.reply (node:electron/js2c/browser_init:2:76322)
    at h (/tmp/.mount_notesng9Fd0W/resources/app/build/electron.js:137:12729)
    at Object.next (/tmp/.mount_notesng9Fd0W/resources/app/build/electron.js:137:13055)
    at Object.next (/tmp/.mount_notesng9Fd0W/resources/app/build/electron.js:74:2492)
    at BrowserWindow.e (/tmp/.mount_notesng9Fd0W/resources/app/build/electron.js:144:9065)
    at BrowserWindow.emit (node:events:526:35)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at s.send (node:electron/js2c/browser_init:2:84285)
    at _.sendToFrame (node:electron/js2c/browser_init:2:69747)
    at e.reply (node:electron/js2c/browser_init:2:76322)
    at h (/tmp/.mount_notesng9Fd0W/resources/app/build/electron.js:137:12729)
    at Object.next (/tmp/.mount_notesng9Fd0W/resources/app/build/electron.js:137:13055)
    at Object.next (/tmp/.mount_notesng9Fd0W/resources/app/build/electron.js:74:2492)
    at BrowserWindow.e (/tmp/.mount_notesng9Fd0W/resources/app/build/electron.js:144:9065)
    at BrowserWindow.emit (node:events:526:35)
```

**Comment by thecodrr** [comment]
Are you using Wayland by any chance?

**Comment by ArGei26** [comment]
No, I'm using Xorg with Nvidia-drivers.
-------- Ursprüngliche Nachricht --------Am 01.05.24 21:37 um Abdullah Atta schrieb :
Are you using Wayland by any chance?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/streetwriters/notesnook/issues/5058#issuecomment-2088990690",
"url": "https://github.com/streetwriters/notesnook/issues/5058#issuecomment-2088990690",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by thecodrr** [comment]
Can you try backing up and clearing the ~/.config/Notesnook directory?

**Comment by ArGei26** [comment]
I tried that already, but it didn't help.
-------- Ursprüngliche Nachricht --------Am 01.05.24 21:55 um Abdullah Atta schrieb :
Can you try backing up and clearing the ~/.config/Notesnook directory?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/streetwriters/notesnook/issues/5058#issuecomment-2089016641",
"url": "https://github.com/streetwriters/notesnook/issues/5058#issuecomment-2089016641",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by ArGei26** [comment]
Unfortunately the error still persists in appimage version 3.0.2.
Same log output.

**Comment by NHodgesVFX** [comment]
I am running into a similar issue. When running the app I get just an empty gray screen when using the flatpak. Or when using the app image I get a white square that glitches when moving the mouse. Interestingly, I noticed if I run the flatpak from the terminal using `flatpak run com.notesnook.Notesnook` the app work mostly fine. The app also works fine if I run the app image from the terminal. For whatever reason clicking or double clicking to start the app doesn't work and results in the above blank screen issue.

Operating System: Kubuntu 22.04
KDE Plasma Version: 5.24.7
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.3
Kernel Version: 6.5.0-41-generic (64-bit)
Graphics Platform: X11
Processors: 32 × AMD Ryzen 9 7950X 16-Core Processor
Memory: 30.5 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 2080 SUPER/PCIe/SSE2
