### ISSUE TITLE
Notes stored locally, "backup failed" -> app not accessible

### ISSUE THREAD

**Issue by the-ungeheuer** [streetwriters/notesnook#5079]
### What happened?

Heya! 
Can't access my notes after update! backup failed. I tapped save & continue and it just shows backup failed and shows the Save & Continue button and is stuck there.

MY GENERAL WORRY IS: 
Pretty sure I only store locally, so any workarounds with reinstall and/or deleting data won't work for me, right? 

Please correct me if I'm wrong! 
I would be really grateful if you comment specifically on the thing with the local storage.
Thanks!

### Steps to reproduce the problem

Update to most recent version (3.0.11), start app and follow instructions (backup)

### Version

V3.0.11

### Platform/OS

Android

### Relevant log output

```shell
Error: Please login to create encrypted backups.
at ?anon_0_ (address at index.android.bundle:1:2871508)
at next (native)
at resume (address at index.android.bundle:1:2868269)
at fulfill (address at index.android.bundle:1:2868448)
at tryCallOne (/root/react-native/packages/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5u5c1a82/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:53:16)
at anonymous (/root/react-native/packages/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5u5c1a82/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:139:27)
at apply (native)
at anonymous (address at index.android.bundle:1:1494525)
at _callTimer (address at index.android.bundle:1:1493517)
at _callReactNativeMicrotasksPass (address at index.android.bundle:1:1493686)
at callReactNativeMicrotasks (address at index.android.bundle:1:1495602)
at __callReactNativeMicrotasks (address at index.android.bundle:1:1391892)
at anonymous (address at index.android.bundle:1:1391018)
at __guard (address at index.android.bundle:1:1391769)
at flushedQueue (address at index.android.bundle:1:1390929)
```

**Comment by ammarahm-ed** [comment]
This has been fixed in the latest version.
