### ISSUE TITLE
Error vault locked: from zoho

### ISSUE THREAD

**Issue by alihamuh** [streetwriters/notesnook#5452]
### What happened?

ERR_VAULT_LOCKED
Error: ERR_VAULT_LOCKED
    at yU.<anonymous> (https://app.notesnook.com/assets/index-963688ad.js:1203:83163)
    at Generator.next (<anonymous>)
    at a (https://app.notesnook.com/assets/index-963688ad.js:1203:79639)

---
Device information:

App version: 3.0.2-c9a8134-desktop
OS: Windows 10 64-bit
Browser: Electron 29.3.1
Pro: true

### Steps to reproduce the problem

---

### Version

3.0.2

### Platform/OS

Windows

### Relevant log output

```shell
---
```

**Comment by ammarahm-ed** [comment]
This has been fixed.
