### ISSUE TITLE
Notesnook Issue with "Something Went Wrong"

### ISSUE THREAD

**Issue by ryanendry** [streetwriters/notesnook#5672]
### What happened?

Hmmm... After update the latest version Notesnook, i got the issue like this on app or browser. Can anyone solve this problem?

![Screenshot 2024-05-17 151626](https://github.com/streetwriters/notesnook/assets/170083503/d6a481ef-a09c-46cf-aacb-e37c0c8413eb)

### Steps to reproduce the problem

![Screenshot 2024-05-17 151626](https://github.com/streetwriters/notesnook/assets/170083503/d6a481ef-a09c-46cf-aacb-e37c0c8413eb)

### Version

3.0.5

### Platform/OS

Windows

### Relevant log output

```shell
Cannot read properties of null (reading 'type')
TypeError: Cannot read properties of null (reading 'type')
    at Bn (https://app.notesnook.com/assets/db-6faecacf8dcb.js:208:42213)
    at tI (https://app.notesnook.com/assets/db-6faecacf8dcb.js:208:42133)
    at Gre (https://app.notesnook.com/assets/db-6faecacf8dcb.js:441:16021)
    at ww (https://app.notesnook.com/assets/index-b4dd57bd.js:793:19538)
    at NC (https://app.notesnook.com/assets/index-b4dd57bd.js:795:44055)
    at _C (https://app.notesnook.com/assets/index-b4dd57bd.js:795:39787)
    at YH (https://app.notesnook.com/assets/index-b4dd57bd.js:795:39715)
    at G0 (https://app.notesnook.com/assets/index-b4dd57bd.js:795:39568)
    at Kv (https://app.notesnook.com/assets/index-b4dd57bd.js:795:35933)
    at D6 (https://app.notesnook.com/assets/index-b4dd57bd.js:795:36737)
```

**Comment by ammarahm-ed** [comment]
This has been fixed.
