### ISSUE TITLE
checkbox bug

### ISSUE THREAD

**Issue by alihamuh** [streetwriters/notesnook#5674]
### What happened?

Index 1 out of range for RangeError: Index 1 out of range for at z.child (https://app.notesnook.com/assets/index-e25dab530d80.js:243:4625) at z.findIndex (https://app.notesnook.com/assets/index-e25dab530d80.js:243:5140) at Em.nodeAt (https://app.notesnook.com/assets/index-e25dab530d80.js:243:16346) at https://app.notesnook.com/assets/index-e25dab530d80.js:396:10895 at https://app.notesnook.com/assets/index-e25dab530d80.js:254:1520 at Object.command (https://app.notesnook.com/assets/index-e25dab530d80.js:251:7706) at HTMLInputElement. (https://app.notesnook.com/assets/index-e25dab530d80.js:396:10856) 

--- Device information: 
App version: 3.0.4-68d57e2-web 
OS: Windows 10 64-bit 
Browser: Chrome 124.0.0.0 
Pro: true

### Steps to reproduce the problem

---

### Version

3.0.4-68d57e2-web 

### Platform/OS

Windows, Chrome/Chromium

**Comment by MarcBollmann** [comment]
If you need any further information I can help you out reproducing the bug
