### ISSUE TITLE
Android app fails to start

### ISSUE THREAD

**Issue by martinfrancois** [streetwriters/notesnook#5722]
### What happened?

On my Android phone I installed the app a long time ago through the play store which worked fine, but recently when I open the app, it asks for my fingerprint, after I scan it, it shows me an error. If I close the error, I only see the title "Notes" with the hamburger menu icon next to it and some placeholders. Once I tap the burger, the side drawer slides open but is empty. Closing / force closing and re-opening the app doesn't help.

I'm using a Samsung S24 Ultra with Android 14. Desktop version works fine.

### Steps to reproduce the problem

1. Open the app
2. Scan fingerprint that was enabled from a login previously
3. Error appears

### Version

3.0.7

### Platform/OS

Android

### Relevant log output

```shell
Error: Database setup failed, could not get database key
    at ?anon_0_ (address at index.android.bundle:1:1932815)
    at next (native)
    at asyncGeneratorStep (address at index.android.bundle:1:3603777)
    at _next (address at index.android.bundle:1:3604047)
    at tryCallOne (/root/react-native/packages/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5u5c1a82/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:53:16)
    at anonymous (/root/react-native/packages/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5u5c1a82/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:139:27)
    at apply (native)
    at anonymous (address at index.android.bundle:1:1494774)
    at _callTimer (address at index.android.bundle:1:1493766)
    at _callReactNativeMicrotasksPass (address at index.android.bundle:1:1493935)
    at callReactNativeMicrotasks (address at index.android.bundle:1:1495851)
    at __callReactNativeMicrotasks (address at index.android.bundle:1:1392131)
    at anonymous (address at index.android.bundle:1:1391257)
    at __guard (address at index.android.bundle:1:1392008)
    at flushedQueue (address at index.android.bundle:1:1391168)
    at invokeCallbackAndReturnFlushedQueue (address at index.android.bundle:1:1391111)
```

**Comment by ammarahm-ed** [comment]
Hi, can you try updating the app to v3.0.8? This issue has been fixed.

**Comment by martinfrancois** [comment]
Can confirm, it is fixed, thanks!
