### ISSUE TITLE
Android app crashed

### ISSUE THREAD

**Issue by NikunjKhangwal** [streetwriters/notesnook#5936]
### What happened?

The app crashed randomly for me once after opening menu of a note and clicking on tags

### Steps to reproduce the problem

Open note menu, click tags

### Version

3.0.9

### Platform/OS

Android

### Relevant log output

```shell
FATAL EXCEPTION: mqt_native_modules
Process: com.streetwriters.notesnook, PID: 26217
com.facebook.react.common.JavascriptException: TypeError: Cannot read property 'setNativeProps' of null, js engine: hermes, stack:
scrollable@1:664388
onBegan@1:664463
anonymous@1:838955
invokeGuardedCallbackImpl@1:1653767
invokeGuardedCallback@1:1653824
invokeGuardedCallbackAndCatchFirstError@1:1653856
executeDispatch@1:1653988
executeDispatchesAndReleaseTopLevel@1:1658229
forEachAccumulated@1:1655471
anonymous@1:1658581
batchedUpdatesImpl@1:1716639
batchedUpdates@1:1658149
_receiveRootNodeIDEvent@1:1658422
receiveEvent@1:1711267
__callFunction@1:1392579
anonymous@1:1391055
__guard@1:1392008
callFunctionReturnFlushedQueue@1:1391013
	at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(Unknown Source:75)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(Unknown Source:148)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(Unknown Source:147)
	at com.facebook.jni.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(Unknown Source:0)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(Unknown Source:37)
	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by ammarahm-ed** [comment]
Fixed with https://github.com/streetwriters/notesnook/commit/3cf46e7ad16be63d7801143e1595a765da1d595c. Issue in a dependency.
