### ISSUE TITLE
File upload failed. Please upgrade to pro [despite being premium member]

### ISSUE THREAD

**Issue by mannyvinny** [streetwriters/notesnook#6194]
### What happened?

I'm getting this error continously despite all my attempts to fix like syncing both android and ios 1 by 1 and even deleting all notes with attachments! But this issue doesn't seems to be going away. 
 Attaching logs feom both ios and android devices
 
`Error: Please upgrade to Pro to upload attachments.
    at ?anon_0_ (address at index.android.bundle:1:1956178)
    at next (native)
    at asyncGeneratorStep (address at index.android.bundle:1:3608960)
    at _next (address at index.android.bundle:1:3609230)
    at tryCallOne (/root/react-native/packages/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5u5c1a82/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:53:16)
    at anonymous (/root/react-native/packages/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5u5c1a82/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:139:27)
    at apply (native)
    at anonymous (address at index.android.bundle:1:1497632)
    at _callTimer (address at index.android.bundle:1:1496624)
    at _callReactNativeMicrotasksPass (address at index.android.bundle:1:1496793)
    at callReactNativeMicrotasks (address at index.android.bundle:1:1498709)
    at __callReactNativeMicrotasks (address at index.android.bundle:1:1394989)
    at anonymous (address at index.android.bundle:1:1394115)
    at __guard (address at index.android.bundle:1:1394866)
    at flushedQueue (address at index.android.bundle:1:1394026)
    at invokeCallbackAndReturnFlushedQueue (address at index.android.bundle:1:1393969)`

ios

`@/private/var/containers/Bundle/Application/9B5F4CA3-784C-4F76-8DB2-8720A33BCA50/Notesnook.app/main.jsbundle:1:3088874
t@/private/var/containers/Bundle/Application/9B5F4CA3-784C-4F76-8DB2-8720A33BCA50/Notesnook.app/main.jsbundle:40:1404390
s@/private/var/containers/Bundle/Application/9B5F4CA3-784C-4F76-8DB2-8720A33BCA50/Notesnook.app/main.jsbundle:40:1404602
@/private/var/containers/Bundle/Application/9B5F4CA3-784C-4F76-8DB2-8720A33BCA50/Notesnook.app/main.jsbundle:40:1118184
@/private/var/containers/Bundle/Application/9B5F4CA3-784C-4F76-8DB2-8720A33BCA50/Notesnook.app/main.jsbundle:40:1118211
@/private/var/containers/Bundle/Application/9B5F4CA3-784C-4F76-8DB2-8720A33BCA50/Notesnook.app/main.jsbundle:1:2363325
v@/private/var/containers/Bundle/Application/9B5F4CA3-784C-4F76-8DB2-8720A33BCA50/Notesnook.app/main.jsbundle:1:2362074
y@/private/var/containers/Bundle/Application/9B5F4CA3-784C-4F76-8DB2-8720A33BCA50/Notesnook.app/main.jsbundle:1:2362469
callReactNativeMicrotasks@/private/var/containers/Bundle/Application/9B5F4CA3-784C-4F76-8DB2-8720A33BCA50/Notesnook.app/main.jsbundle:1:2364712
value@/private/var/containers/Bundle/Application/9B5F4CA3-784C-4F76-8DB2-8720A33BCA50/Notesnook.app/main.jsbundle:1:2204813
@/private/var/containers/Bundle/Application/9B5F4CA3-784C-4F76-8DB2-8720A33BCA50/Notesnook.app/main.jsbundle:1:2202915
value@/private/var/containers/Bundle/Application/9B5F4CA3-784C-4F76-8DB2-8720A33BCA50/Notesnook.app/main.jsbundle:1:2204461
value@/private/var/containers/Bundle/Application/9B5F4CA3-784C-4F76-8DB2-8720A33BCA50/Notesnook.app/main.jsbundle:1:2202873`

### Steps to reproduce the problem

Be a non premium

Upgrade to premium in ios> attach image in any jote> check android or desktop app> done
Now all 3 devices will give same issue of upgrade to pro. (Despite app showing premium status)

### Version

Latest available in app stores

### Platform/OS

Windows, iOS, Android

**Comment by thecodrr** [comment]
This has been fixed in v3.0.12, I think. The error should go away after an hour by itself in previous versions.
