### ISSUE TITLE
Nook 3.0.13 fails to launch (crash)

### ISSUE THREAD

**Issue by serrq** [streetwriters/notesnook#6383]
Android 14
OnePlus CPH2399
Nook 3.0.13 (fdroid)

Unable to launch the app. It always crashes.

![1000117838](https://github.com/user-attachments/assets/65be2eae-3206-4f2d-a248-88b151e1b168)

**Comment by ocrammaig** [comment]
I have the same issue, here's the error log


```
type: crash
osVersion: google/raven/raven:14/AP2A.240805.005.F1/2024080600:user/release-keys
package: com.streetwriters.notesnook:15113
process: com.streetwriters.notesnook
processUptime: 194 + 239 ms
installer: com.machiav3lli.fdroid

java.lang.SecurityException: com.streetwriters.notesnook: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3192)
	at android.os.Parcel.createException(Parcel.java:3176)
	at android.os.Parcel.readException(Parcel.java:3152)
	at android.os.Parcel.readException(Parcel.java:3094)
	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5875)
	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1885)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1825)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1813)
	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:757)
	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:757)
	at com.github.yamill.orientation.OrientationModule.onHostResume(Unknown Source:23)
	at com.facebook.react.bridge.ReactContext.onHostResume(Unknown Source:34)
	at com.facebook.react.ReactInstanceManager.moveToResumedLifecycleState(Unknown Source:26)
	at com.facebook.react.ReactInstanceManager.moveReactContextToCurrentLifecycleState(Unknown Source:8)
	at com.facebook.react.ReactInstanceManager.lambda$setupReactContext$3(Unknown Source:0)
	at com.facebook.react.ReactInstanceManager.f(SourceFile:1)
	at com.facebook.react.r.run(SourceFile:1)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8623)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:14557)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2656)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2826)
	at android.os.Binder.execTransactInternal(Binder.java:1529)
	at android.os.Binder.execTransact(Binder.java:1468)
```

**Comment by landry314** [comment]
me too. please fix i am lost without my app!

**Comment by alvanrahimli** [comment]
The same is happening for mee. Here is crash dump: on Pixel 7 woth latest Graphene OS.

```
type: crash
osVersion: google/panther/panther:14/AP2A.240805.005/2024080600:user/release-keys
package: com.streetwriters.notesnook:15113
process: com.streetwriters.notesnook
processUptime: 288 + 335 ms
installer: com.looker.droidify

java.lang.SecurityException: com.streetwriters.notesnook: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3192)
	at android.os.Parcel.createException(Parcel.java:3176)
	at android.os.Parcel.readException(Parcel.java:3152)
	at android.os.Parcel.readException(Parcel.java:3094)
	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5875)
	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1885)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1825)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1813)
	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:757)
	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:757)
	at com.github.yamill.orientation.OrientationModule.onHostResume(Unknown Source:23)
	at com.facebook.react.bridge.ReactContext.onHostResume(Unknown Source:34)
	at com.facebook.react.ReactInstanceManager.moveToResumedLifecycleState(Unknown Source:26)
	at com.facebook.react.ReactInstanceManager.moveReactContextToCurrentLifecycleState(Unknown Source:8)
	at com.facebook.react.ReactInstanceManager.lambda$setupReactContext$3(Unknown Source:0)
	at com.facebook.react.ReactInstanceManager.f(SourceFile:1)
	at com.facebook.react.r.run(SourceFile:1)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8623)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:14557)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2656)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2826)
	at android.os.Binder.execTransactInternal(Binder.java:1529)
	at android.os.Binder.execTransact(Binder.java:1468)
```

**Comment by charlag** [comment]
it might be f-droid version only

**Comment by trolles** [comment]
Same problem here. Afraid to downgrade and lose latest changes.

**Comment by ammarahm-ed** [comment]
Hi everyone, a new release is in pipeline on fdroid which should fix the issue. However it might take several days.
