### ISSUE TITLE
Adding a Callout inside another Callout caused a crash

### ISSUE THREAD

**Issue by alihamuh** [streetwriters/notesnook#6595]
### What happened?

. I accidentally added a Callout inside another Callout and the page went blank, showing the following error:

---
Device information:

App version: 3.0.17-6def76e-desktop
OS: Linux 64-bit
Browser: Electron 29.3.1
Pro: true

### Steps to reproduce the problem

. I accidentally added a Callout inside another Callout and the page went blank, showing the following error:

### Version

3.0.17-6def76e-desktop

### Platform/OS

Linux

### Relevant log output

```shell
Called contentMatchAt on a node with invalid content
Error: Called contentMatchAt on a node with invalid content
at pg.contentMatchAt (https://app.notesnook.com/assets/app-BcHQFvdxrxpV.js:6:74102)
at jA (https://app.notesnook.com/assets/app-BcHQFvdxrxpV.js:14:1903)
at _9 (https://app.notesnook.com/assets/app-BcHQFvdxrxpV.js:13:50770)
at https://app.notesnook.com/assets/app-BcHQFvdxrxpV.js:17:6498
at Object.joinBackward (https://app.notesnook.com/assets/app-BcHQFvdxrxpV.js:14:8275)
at Array. (https://app.notesnook.com/assets/app-BcHQFvdxrxpV.js:17:24463)
at https://app.notesnook.com/assets/app-BcHQFvdxrxpV.js:17:3676
at Object.first (https://app.notesnook.com/assets/app-BcHQFvdxrxpV.js:14:7241)
at t (https://app.notesnook.com/assets/app-BcHQFvdxrxpV.js:17:24059)
at https://app.notesnook.com/assets/app-BcHQFvdxrxpV.js:15:4346
```

**Comment by ammarahm-ed** [comment]
Can't reproduce this on the latest version.
