### ISSUE TITLE
App crashed on changing text/background color: zoho

### ISSUE THREAD

**Issue by alihamuh** [streetwriters/notesnook#6842]
### What happened?

I was working on a table and changed the color of the background, then I changed the color of the text and the app crashed.
Below is the message displayed. Please, help. I need to work on the app today.
Thank you

Position 2501 out of range
RangeError: Position 2501 out of range
    at wa.resolve (https://app.notesnook.com/assets/use-auto-updater-CS5lM6Vs6cI-.js:6:126150)
    at Xf.resolveNoCache (https://app.notesnook.com/assets/use-auto-updater-CS5lM6Vs6cI-.js:6:129070)
    at L5 (https://app.notesnook.com/assets/use-auto-updater-CS5lM6Vs6cI-.js:14:37836)
    at S5.handleDOMChange (https://app.notesnook.com/assets/use-auto-updater-CS5lM6Vs6cI-.js:14:42290)
    at S5.flush (https://app.notesnook.com/assets/use-auto-updater-CS5lM6Vs6cI-.js:14:31893)
    at S5.observer (https://app.notesnook.com/assets/use-auto-updater-CS5lM6Vs6cI-.js:14:28736)

---
Device information:

App version: 3.0.19-22dcba840-web
OS: Chrome OS 64-bit
Browser: Chrome 130.0.0.0
Pro: true

### Steps to reproduce the problem

---

### Version

3.0.19-22dcba840-web

### Platform/OS

Chrome/Chromium

### Relevant log output

---

**Comment by thecodrr** [comment]
No longer reproducible.
