### ISSUE TITLE
can't compile / react dep / Buffer as Buffer2

### ISSUE THREAD

**Issue by oeai** [streetwriters/notesnook#6854]
### What happened?

Hi. i wanted to see the code and try to compile - but it's not compiling.
And also i see - there is a lot of issues, so i decided to describe some.
i think, that the problem is in different libraries (of course) that are used for different devices and the only way is to include those in distribution.
The one error i had was about react lib - some parts has 8.0.39 dep and react.dom - 8.0.17 - it wasn't changed maybe, but if react is used, it has to be the same. And that react dependency wasn't set in main part json on top. does it need yarn?

```
 "devDependencies": {
    "@react-native-community/cli": "8.0.17"
```
without this i had error ending with pngjs and more

then (after react written) when it compiles i got error with vitejs with some wrong export value for ( Buffer as Buffer2 ) something, because some browser can't use external value. i'm first time trying to use that nodejs and react and electron to build

` ×  nx run @notesnook/vericrypt:build`

```
▲ [WARNING] Duplicate key "@types/react" in object literal [duplicate-object-key]

    package.json:8:4:
      8 │     "@types/react": "^18.2.17",
        ╵     ~~~~~~~~~~~~~~

  The original key "@types/react" is here:

    package.json:7:4:
      7 │     "@types/react": "^18.2.39",
        ╵     ~~~~~~~~~~~~~~

Browserslist: caniuse-lite is outdated
```

```
"Buffer" is not exported by "__vite-browser-external", imported by "../../packages/sodium/dist/node.mjs".
file: D:/Projects/Side/notesnook-master/packages/sodium/dist/node.mjs:54:9

52:   crypto_secretstream_xchacha20poly1305_TAG_MESSAGE
53: } from "sodium-native";
54: import { Buffer as Buffer2 } from "node:buffer";
             ^
55:
56: // src/types.ts
```

so without  vericrypt - it's not starting and it's all about libs integrity
same error goes for theme-builder

so 2 of packages can' be compiled and i used LTS nodejs i guess it's 20 and i tried 22,16,18 - it has some wrongly set dependencies like one lib need <17 and other wants > 14 and another >20 - i mean, you should check i really 
and also, in terms of production - maybe you can just include some needed parts of the code inside ?
well, this can be a workaround for different setups and versions and you can exclude some parts maybe to make this code less big or set it up as integrity lib maybe

### Steps to reproduce the problem

try to get the code to clean VS Code and see dependencies and how the npm install works

### Version

it was latest master, but apps/desktop shows 3.0.18

### Platform/OS

Windows

### Relevant log output

```shell
[vite:worker] "Buffer" is not exported by "__vite-browser-external", imported by "../../packages/sodium/dist/node.mjs".
file: D:/Projects/Side/notesnook-master/apps/web/src/interfaces/opfs.worker.ts?worker:54:9
52:   crypto_secretstream_xchacha20poly1305_TAG_MESSAGE
53: } from "sodium-native";
54: import { Buffer as Buffer2 } from "node:buffer";
```

**Comment by greatwolf** [comment]
I'm wondering did you run into any libsodium dependency issues? When I try to do the build for web part, I followed basically the workflow here https://github.com/streetwriters/notesnook/blob/master/.github/workflows/web.publish.yml. But at the end of it I always get an issue with sodium not being found at some point causing the whole build to not proceed.

```
Error: error occured in dts build
    at Worker.<anonymous> (/home/debian/notesnook/node_modules/tsup/dist/index.js:1543:26)
    at Worker.emit (node:events:517:28)
    at MessagePort.<anonymous> (node:internal/worker:256:53)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:786:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)
DTS Build error
RollupError: [plugin dts] src/components/icon/index.tsx: Failed to compile. Check the logs above.
    at getRollupError (/home/debian/notesnook/node_modules/rollup/dist/shared/parseAst.js:282:41)
    at Object.error (/home/debian/notesnook/node_modules/rollup/dist/shared/parseAst.js:278:42)
    at Object.error (/home/debian/notesnook/node_modules/rollup/dist/shared/rollup.js:815:32)
    at Object.error (/home/debian/notesnook/node_modules/rollup/dist/shared/rollup.js:19970:42)
    at generateDtsFromTs (/home/debian/notesnook/node_modules/tsup/dist/rollup.js:7990:22)
    at /home/debian/notesnook/node_modules/tsup/dist/rollup.js:7997:59
    at _nullishCoalesce (/home/debian/notesnook/node_modules/tsup/dist/rollup.js:1:473)
    at Object.transform (/home/debian/notesnook/node_modules/tsup/dist/rollup.js:7997:18)
    at /home/debian/notesnook/node_modules/rollup/dist/shared/rollup.js:1000:40

 ——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Ran target build for project @notesnook/web and 13 task(s) they depend on (2m)

    ✖    3/9 failed
    ✔    6/9 succeeded [6 read from cache]
```

this was tried on oracle cloud using clean debian 12 setup.

**Comment by oeai** [comment]
Sure it's different for W10 with VS Code

**Comment by thecodrr** [comment]
Should be fixed now.
