### ISSUE TITLE
Monograph can't display embed image (og.png)

### ISSUE THREAD

**Issue by ibaraki-douji** [streetwriters/notesnook#6973]
### What happened?

Self-hosted (monograph version 1.1.1)

When i try to send a monograph on Discord the embed does not show the image.

### Steps to reproduce the problem

Create a note, publish it as a monograph, and post the link on a discord channel

### Version

v3.0.22

### Platform/OS

Linux, Windows

### Relevant log output

```shell
GET /api/health 200 - - 1.800 ms
Error: ENOENT: no such file or directory, open 'spam-cache'
    at open (node:internal/fs/promises:639:25)
    at readFile (node:internal/fs/promises:1242:14)
    at Module.read (file:///home/node/app/build/server/assets/fs-BKBHnzsr.js:4:23)
    at isSpamCached (file:///home/node/app/build/server/assets/server-build-J5CL24zL.js:121631:18)
    at loader (file:///home/node/app/build/server/assets/server-build-J5CL24zL.js:123112:24)
    at Object.callRouteLoader (/home/node/app/node_modules/@remix-run/server-runtime/dist/data.js:59:16)
    at /home/node/app/node_modules/@remix-run/router/router.ts:4899:19
    at callLoaderOrAction (/home/node/app/node_modules/@remix-run/router/router.ts:4963:16)
    at async Promise.all (index 0)
    at defaultDataStrategy (/home/node/app/node_modules/@remix-run/router/router.ts:4772:17) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'spam-cache'
}
Error: ENOENT: no such file or directory, open 'rules'
    at open (node:internal/fs/promises:639:25)
    at readFile (node:internal/fs/promises:1242:14)
    at Module.read (file:///home/node/app/build/server/assets/fs-BKBHnzsr.js:4:23)
    at isSpam (file:///home/node/app/build/server/assets/server-build-J5CL24zL.js:121638:19)
    at loader (file:///home/node/app/build/server/assets/server-build-J5CL24zL.js:123116:40)
    at Object.callRouteLoader (/home/node/app/node_modules/@remix-run/server-runtime/dist/data.js:59:16)
    at /home/node/app/node_modules/@remix-run/router/router.ts:4899:19
    at callLoaderOrAction (/home/node/app/node_modules/@remix-run/router/router.ts:4963:16)
    at async Promise.all (index 0)
    at defaultDataStrategy (/home/node/app/node_modules/@remix-run/router/router.ts:4772:17) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'rules'
}
GET /api/health 200 - - 1.372 ms
GET /671f6cb825f6ad2e3554de1b?a=a 200 - - 491.948 ms
GET /api/og.png?title=MonoGraph&description=W2RhdGE6aW1hZ2UvcG5nO2Jhc2U2NCxpVkJPUncwS0dnb0FBQUFOU1VoRVVnQUFCWmtBQUFGbUNBWUFBQUFQdUpTQUFBQUFBWE5TUjBJQXJzNGM2UUFBSUFCSlJFRlVlRjZrdlZtdmJFdVNKbVFySXZad3poM3labFYyVjZ0YlNOWDlBaEwvZ3o5QUkxcmlHZXFsaXdjZVFTb2txbjRXcUlYRU02b3FRRWdJSVlTYUlhdXpidDU3aGozRnNKRE5uNW43aXRnMysxVGQzQkVyMW5JM3QrRXpjM056WDh0LzloZC9mYm1zaDJXbC9iclFaYUYxV1M4WFdzNDdXay9ubFhaMFdlNzNLejN1RjlydkZxS0Y3TjlLUkt2K3YvNlJ2M3FKUDhTTi9nQXRmLi4u&date=2024-11-23+19%3A57 200 - - 443.676 ms
AbortError: The operation was aborted
    at Sharp.<anonymous> (node:internal/webstreams/adapters:442:19)
    at Sharp.<anonymous> (node:internal/util:539:20)
    at Sharp.onclose (node:internal/streams/end-of-stream:158:25)
    at Sharp.emit (node:events:518:28)
    at Sharp.<anonymous> (/home/node/app/node_modules/sharp/lib/output.js:1509:35)
    at Sharp.emit (node:events:530:35)
    at endReadableNT (node:internal/streams/readable:1698:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
GET /api/og.png?title=MonoGraph&description=W2RhdGE6aW1hZ2UvcG5nO2Jhc2U2NCxpVkJPUncwS0dnb0FBQUFOU1VoRVVnQUFCWmtBQUFGbUNBWUFBQUFQdUpTQUFBQUFBWE5TUjBJQXJzNGM2UUFBSUFCSlJFRlVlRjZrdlZtdmJFdVNKbVFySXZad3poM3labFYyVjZ0YlNOWDlBaEwvZ3o5QUkxcmlHZXFsaXdjZVFTb2txbjRXcUlYRU02b3FRRWdJSVlTYUlhdXpidDU3aGozRnNKRE5uNW43aXRnMysxVGQzQkVyMW5JM3QrRXpjM056WDh0LzloZC9mYm1zaDJXbC9iclFaYUYxV1M4WFdzNDdXay9ubFhaMFdlNzNLejN1RjlydkZxS0Y3TjlLUkt2K3YvNlJ2M3FKUDhTTi9nQXRmLi4u&date=2024-11-23+19%3A57 200 - - 444.220 ms
AbortError: The operation was aborted
    at Sharp.<anonymous> (node:internal/webstreams/adapters:442:19)
    at Sharp.<anonymous> (node:internal/util:539:20)
    at Sharp.onclose (node:internal/streams/end-of-stream:158:25)
    at Sharp.emit (node:events:518:28)
    at Sharp.<anonymous> (/home/node/app/node_modules/sharp/lib/output.js:1509:35)
    at Sharp.emit (node:events:530:35)
    at endReadableNT (node:internal/streams/readable:1698:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
GET /api/health 200 - - 3.099 ms
GET /api/health 200 - - 2.040 ms
GET /api/health 200 - - 1.137 ms
```

**Comment by thecodrr** [comment]
Fixed.
