### ISSUE TITLE
SqliteError: near "?": syntax error

### ISSUE THREAD

**Issue by vhaudiquet** [streetwriters/notesnook#7047]
### What happened?

When I open the application, it starts to load, I see my notes and before I can do anything I see :

```
near "?": syntax error (query: select count("id") as "count" from "notes" where ("dateDeleted" is null or "dateDeleted" == 0) and ("deleted" is null or "deleted" == 0) and "id" in ?)
SqliteError: near "?": syntax error (query: select count("id") as "count" from "notes" where ("dateDeleted" is null or "dateDeleted" == 0) and ("deleted" is null or "deleted" == 0) and "id" in ?)
    at Database.prepare (/usr/lib/notesnook/app/node_modules/better-sqlite3-multiple-ciphers/lib/methods/wrappers.js:5:21)
    at z.<anonymous> (https://app.notesnook.com/assets/sqlite.worker.desktop-CP9v2gK6.js:1:884)
    at Generator.next (<anonymous>)
    at https://app.notesnook.com/assets/sqlite.worker.desktop-CP9v2gK6.js:1:298
    at new Promise (<anonymous>)
    at g (https://app.notesnook.com/assets/sqlite.worker.desktop-CP9v2gK6.js:1:95)
    at z.prepare (https://app.notesnook.com/assets/sqlite.worker.desktop-CP9v2gK6.js:1:701)
    at z.<anonymous> (https://app.notesnook.com/assets/sqlite.worker.desktop-CP9v2gK6.js:1:1312)
    at Generator.next (<anonymous>)
    at https://app.notesnook.com/assets/sqlite.worker.desktop-CP9v2gK6.js:1:298
```

Sometimes, if I "Reload app" multiple times, it then vanishes. Maybe it is some kind of race condition ? Why would the table variable be initialized with '?' ? I don't understand

### Steps to reproduce the problem

I'm using notesnook on Arch linux. I tried the version compiled from source (aur/notesnook) and binary (aur/notesnook-bin).

### Version

Compiled from source

### Platform/OS

Linux

### Relevant log output

```shell

```

**Comment by vhaudiquet** [comment]
Little update: it never works either on the Web App (app.notesnook.com) or the desktop app **after** connecting to the server (if I access it offline, it works). It syncs my notes and then crashes with the error.
On the mobile app, it **always** works and I have never had this issue.

**Comment by vhaudiquet** [comment]
Nice to see this closed as completed ! Would you mind sharing commit hash (maybe it is not yet merged to main) ?
I would really like to be able to test it and make it work for me :)
Thank you for your work !

**Comment by 01zulfi** [comment]
Hello, I don't think this issue has been explicitly addressed. But could you try with the latest versions again? If you're still getting the bug, I can reopen the issue.
