### ISSUE TITLE
Unknown connection errors during sync

### ISSUE THREAD

**Issue by candroid-man** [streetwriters/notesnook#706]
```
2022-07-21T00:39:40.906Z | ERROR | Error: Cannot start a HubConnection that is not in the 'Disconnected' state.
    at ?anon_0_ (address at index.android.bundle:1:74108)
    at next (native)
    at asyncGeneratorStep (address at index.android.bundle:1:2674463)
    at _next (address at index.android.bundle:1:2674733)
    at anonymous (address at index.android.bundle:1:2674685)
    at tryCallTwo (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/6w2n2p31/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:61:9)
    at doResolve (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/6w2n2p31/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:216:25)
    at Promise (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/6w2n2p31/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:82:14)
    at anonymous (address at index.android.bundle:1:2674606)
    at apply (native)
    at _startWithStateTransitions (address at index.android.bundle:1:73737)
    at start (address at index.android.bundle:1:73660)
    at ?anon_0_ (address at index.android.bundle:1:287477)
    at next (native)
    at asyncGeneratorStep (address at index.android.bundle:1:2674463)
    at _next (address at index.android.bundle:1:2674733)
    at tryCallOne (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/6w2n2p31/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:53:16)
    at anonymous (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/6w2n2p31/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:139:27)
    at apply (native)
    at anonymous (address at index.android.bundle:1:1279424)
    at _callTimer (address at index.android.bundle:1:1278416)
    at _callReactNativeMicrotasksPass (address at index.android.bundle:1:1278585)
    at callReactNativeMicrotasks (address at index.android.bundle:1:1280508)
    at __callReactNativeMicrotasks (address at index.android.bundle:1:1176800)
    at anonymous (address at index.android.bundle:1:1175924)
    at __guard (address at index.android.bundle:1:1176677)
    at flushedQueue (address at index.android.bundle:1:1175835)
    at callFunctionReturnFlushedQueue (address at index.android.bundle:1:1175691) [11586180ms] 
```

```
2022-07-21T00:39:40.849Z | ERROR | [Sync]: Error: Connection closed.
    at anonymous (address at index.android.bundle:1:284159)
    at apply (native)
    at anonymous (address at index.android.bundle:1:79378)
    at forEach (native)
    at _completeClose (address at index.android.bundle:1:79262)
    at ?anon_0_ (address at index.android.bundle:1:80562)
    at throw (native)
    at asyncGeneratorStep (address at index.android.bundle:1:2674463)
    at _throw (address at index.android.bundle:1:2674780)
    at tryCallOne (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/6w2n2p31/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:53:16)
    at anonymous (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/6w2n2p31/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:139:27)
    at apply (native)
    at anonymous (address at index.android.bundle:1:1279424)
    at _callTimer (address at index.android.bundle:1:1278416)
    at _callReactNativeMicrotasksPass (address at index.android.bundle:1:1278585)
    at callReactNativeMicrotasks (address at index.android.bundle:1:1280508)
    at __callReactNativeMicrotasks (address at index.android.bundle:1:1176800)
    at anonymous (address at index.android.bundle:1:1175924)
    at __guard (address at index.android.bundle:1:1176677)
    at flushedQueue (address at index.android.bundle:1:1175835)
    at callFunctionReturnFlushedQueue (address at index.android.bundle:1:1175691) [255ms] 
```

```
2022-07-21T00:39:40.843Z | ERROR | [SignalR::SyncHub]: Error: Failed to start the HttpConnection before stop() was called.
    at log (address at index.android.bundle:1:283203)
    at ?anon_0_ (address at index.android.bundle:1:64355)
    at next (native)
    at asyncGeneratorStep (address at index.android.bundle:1:2674463)
    at _next (address at index.android.bundle:1:2674733)
    at tryCallOne (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/6w2n2p31/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:53:16)
    at anonymous (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/6w2n2p31/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:139:27)
    at apply (native)
    at anonymous (address at index.android.bundle:1:1279424)
    at _callTimer (address at index.android.bundle:1:1278416)
    at _callReactNativeMicrotasksPass (address at index.android.bundle:1:1278585)
    at callReactNativeMicrotasks (address at index.android.bundle:1:1280508)
    at __callReactNativeMicrotasks (address at index.android.bundle:1:1176800)
    at anonymous (address at index.android.bundle:1:1175924)
    at __guard (address at index.android.bundle:1:1176677)
    at flushedQueue (address at index.android.bundle:1:1175835)
    at callFunctionReturnFlushedQueue (address at index.android.bundle:1:1175691) [11586117ms] 
```

```
2022-07-20T21:47:36.085Z | ERROR | [SignalR::SyncHub]: Error: Failed to start the connection: Error: WebSocket failed to connect. The connection could not be found on the server, either the endpoint may not be a SignalR endpoint, the connection ID is not present on the server, or there is a proxy blocking WebSockets. If you have multiple servers check that sticky sessions are enabled.
    at log (address at index.android.bundle:1:283203)
    at ?anon_0_ (address at index.android.bundle:1:66109)
    at throw (native)
    at asyncGeneratorStep (address at index.android.bundle:1:2674463)
    at _throw (address at index.android.bundle:1:2674780)
    at tryCallOne (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/6w2n2p31/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:53:16)
    at anonymous (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/6w2n2p31/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:139:27)
    at apply (native)
    at anonymous (address at index.android.bundle:1:1279424)
    at _callTimer (address at index.android.bundle:1:1278416)
    at _callReactNativeMicrotasksPass (address at index.android.bundle:1:1278585)
    at callReactNativeMicrotasks (address at index.android.bundle:1:1280497)
    at __callReactNativeMicrotasks (address at index.android.bundle:1:1176800)
    at anonymous (address at index.android.bundle:1:1175924)
    at __guard (address at index.android.bundle:1:1176677)
    at flushedQueue (address at index.android.bundle:1:1175835)
    at callFunctionReturnFlushedQueue (address at index.android.bundle:1:1175691) [1261359ms] 
```

**Comment by thecodrr** [comment]
These are now properly handled in Android v2.1.7
