### ISSUE TITLE
Build issues from new git clone

### ISSUE THREAD

**Issue by SimpleVictor** [streetwriters/notesnook#7112]
### What happened?

I'm getting the error below when running `npm run start:web`

```
✘ [ERROR] Cannot start service: Host version "0.20.2" does not match binary version "0.23.1"
```

**Environments**
Node version: `v18.17.0`
NPM: `9.6.7`

### Steps to reproduce the problem

1. git clone https://github.com/streetwriters/notesnook.git
2. cd notesnook
3. npm install
4. npm run start:web

### Version

v3.0.22

### Platform/OS

macOS

### Relevant log output

```shell
✘ [ERROR] Cannot start service: Host version "0.20.2" does not match binary version "0.23.1"
```

**Comment by kalikid021** [comment]
I'm having the same issue on Ubuntu 24.04

Node 22.13.0
NPM 10.9.2

`> build:web
> nx build @notesnook/web


   ✔    13/13 dependent project tasks succeeded [13 read from cache]

   Hint: you can run the command with --verbose to see the full dependent project outputs

 ——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————


> nx run @notesnook/web:build


> @notesnook/web@3.0.23 build
> cross-env PLATFORM=web vite build

✘ [ERROR] Cannot start service: Host version "0.21.5" does not match binary version "0.23.1"

1 error
failed to load config from /opt/notesnook/notesnook/apps/web/vite.config.ts
error during build:
Error: The service was stopped: write EPIPE
    at /opt/notesnook/notesnook/apps/web/node_modules/vite/node_modules/esbuild/lib/main.js:968:34
    at responseCallbacks.<computed> (/opt/notesnook/notesnook/apps/web/node_modules/vite/node_modules/esbuild/lib/main.js:622:9)
    at afterClose (/opt/notesnook/notesnook/apps/web/node_modules/vite/node_modules/esbuild/lib/main.js:613:28)
    at /opt/notesnook/notesnook/apps/web/node_modules/vite/node_modules/esbuild/lib/main.js:1983:18
    at onwriteError (node:internal/streams/writable:605:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:92:21)

 ——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Ran target build for project @notesnook/web and 13 task(s) they depend on (1s)

    ✖    1/14 failed
    ✔    13/14 succeeded [13 read from cache]

   View structured, searchable error logs at https://nx.app/runs/qvcFj5p6ji`
