### ISSUE TITLE
Error initializing database

### ISSUE THREAD

**Issue by localjanitor** [streetwriters/notesnook#7239]
### What happened?

App is blank with just the message at the bottom saying:

Error initializing database
Database setup failed, could not get database key

### Steps to reproduce the problem

No idea, it just happens after a few days after reinstalling each time. I've been using the web version in place.

### Version

3.0.25

### Platform/OS

Android

### Relevant log output

```shell
Error: Database setup failed, could not get database key
    at ?anon_0_ (address at index.android.bundle:1:2141703)
    at next (native)
    at asyncGeneratorStep (address at index.android.bundle:1:3817963)
    at _next (address at index.android.bundle:1:3818218)
    at tryCallOne (address at InternalBytecode.js:1:1180)
    at anonymous (address at InternalBytecode.js:1:1874)
    at apply (native)
    at anonymous (address at index.android.bundle:1:1679629)
    at _callTimer (address at index.android.bundle:1:1678623)
    at _callReactNativeMicrotasksPass (address at index.android.bundle:1:1678772)
    at callReactNativeMicrotasks (address at index.android.bundle:1:1680705)
    at __callReactNativeMicrotasks (address at index.android.bundle:1:1573168)
    at anonymous (address at index.android.bundle:1:1572288)
    at __guard (address at index.android.bundle:1:1573042)
    at flushedQueue (address at index.android.bundle:1:1572199)
    at invokeCallbackAndReturnFlushedQueue (address at index.android.bundle:1:1572142)
```

**Comment by ammarahm-ed** [comment]
Hi, is your android device by any chance rooted?

**Comment by localjanitor** [comment]
Hey yeah, it is rooted.

**Comment by atomicretro** [comment]
I'm also getting this error! Also on Android, but using Lineage OS. My phone isn't rooted.

Phone: Pixel 4a
Android version: 14
OS: LineageOS 21-20241121-NIGHTLY-sunfish
Notesnook version: 3.0.26

```
Error: Unknown error: Could not decrypt bytes: Keystore operation failed
    at promiseMethodWrapper (address at index.android.bundle:1:1575052)
    at getInternetCredentials (address at index.android.bundle:1:1017482)
    at ?anon_0_ (address at index.android.bundle:1:2136446)
    at next (native)
    at asyncGeneratorStep (address at index.android.bundle:1:3817967)
    at _next (address at index.android.bundle:1:3818222)
    at tryCallOne (address at InternalBytecode.js:1:1180)
    at anonymous (address at InternalBytecode.js:1:1874)
    at apply (native)
    at anonymous (address at index.android.bundle:1:1679611)
    at _callTimer (address at index.android.bundle:1:1678605)
    at _callReactNativeMicrotasksPass (address at index.android.bundle:1:1678754)
    at callReactNativeMicrotasks (address at index.android.bundle:1:1680676)
    at __callReactNativeMicrotasks (address at index.android.bundle:1:1573146)
    at anonymous (address at index.android.bundle:1:1572266)
    at __guard (address at index.android.bundle:1:1573020)
    at flushedQueue (address at index.android.bundle:1:1572177)
    at invokeCallbackAndReturnFlushedQueue (address at index.android.bundle:1:1572120)
```

**Comment by EAGzzyCSL** [comment]
Same issue with log

```plain
M4.a: Unknown error: Could not decrypt bytes: Keystore operation failed
    at promiseMethodWrapper (address at index.android.bundle:1:2953934)
    at getInternetCredentials (address at index.android.bundle:1:3512189)
    at ?anon_0_ (address at index.android.bundle:1:3541003)
    at next (native)
    at asyncGeneratorStep (address at index.android.bundle:1:894097)
    at _next (address at index.android.bundle:1:894353)
    at tryCallOne (address at InternalBytecode.js:1:1180)
    at anonymous (address at InternalBytecode.js:1:1874)
    at apply (native)
    at anonymous (address at index.android.bundle:1:3123369)
    at _callTimer (address at index.android.bundle:1:3122581)
    at _callReactNativeMicrotasksPass (address at index.android.bundle:1:3122730)
    at callReactNativeMicrotasks (address at index.android.bundle:1:3124434)
    at __callReactNativeMicrotasks (address at index.android.bundle:1:3049717)
    at anonymous (address at index.android.bundle:1:3048837)
    at __guard (address at index.android.bundle:1:3049591)
    at flushedQueue (address at index.android.bundle:1:3048748)
    at invokeCallbackAndReturnFlushedQueue (address at index.android.bundle:1:3048691)
```

This usually occurs when the app has not been launched for a long time (it is suspected that the background processes of the app have been killed at this time), and it can be resolved by restarting the app several times.


- Phone: Xiaomi 15 Ultra
- Android version: 16
- OS: HyperOS 3.0.6.0.WOACNXM
- Notesnook version: 3.3.9

**Comment by ammarahm-ed** [comment]
The issue usually occurs after an OS update where something changes in the keystore and corrupts the data stored. Reinstalling the app fixes it.
