### ISSUE TITLE
Error: Unknown content type: "undefined"

### ISSUE THREAD

**Issue by ri3otto** [streetwriters/notesnook#809]
### What happened?

So this happened when I installed the app on a new device. Now the syncing is completely unavailable. Also the syncing is always stuck on 98%

### Steps to reproduce the problem

Just start syncing

### Version

2.1.4

### Platform/OS

Windows, macOS, iOS, Android

### Relevant log output

```shell
Error: Unknown content type: "undefined". Please report this error at support@streetwriters.co.
at getContentFromData (address at index.android.bundle:1:344980)
at ?anon_0_ (address at index.android.bundle:1:318956)
at next (native)
at asyncGeneratorStep (address at index.android.bundle:1:2678820)
at _next (address at index.android.bundle:1:2679090)
at anonymous (address at index.android.bundle:1:2679042)
at tryCallTwo (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/2w202i6w/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:61:9)
at doResolve (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/2w202i6w/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:216:25)
at Promise (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/2w202i6w/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:82:14)
at anonymous (address at index.android.bundle:1:2678963)
at apply (native)
at extractAttachments (address at index.android.bundle:1:318849)
at ?anon_0_ (address at index.android.bundle:1:317506)
at next (native)
at asyncGeneratorStep (address at index.android.bundle:1:2678820)
at _next (address at index.android.bundle:1:2679090)
at anonymous (address at index.android.bundle:1:2679042)
at tryCallTwo (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/2w202i6w/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:61:9)
at doResolve (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/2w202i6w/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:216:25)
at Promise (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/2w202i6w/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:82:14)
at anonymous (address at index.android.bundle:1:2678963)
at apply (native)
at add (address at index.android.bundle:1:316912)
at set (address at index.android.bundle:1:290907)
at ?anon_0_ (address at index.android.bundle:1:292787)
at next (native)
at asyncGeneratorStep (address at index.android.bundle:1:2678820)
at _next (address at index.android.bundle:1:2679090)
at tryCallOne (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/2w202i6w/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:53:16)
at anonymous (/root/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/2w202i6w/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:139:27)
at apply (native)
at anonymous (address at index.android.bundle:1:1281909)
at _callTimer (address at index.android.bundle:1:1280901)
at _callReactNativeMicrotasksPass (address at index.android.bundle:1:1281070)
at callReactNativeMicrotasks (address at index.android.bundle:1:1282993)
at __callReactNativeMicrotasks (address at index.android.bundle:1:1179319)
at anonymous (address at index.android.bundle:1:1178443)
at __guard (address at index.android.bundle:1:1179196)
at flushedQueue (address at index.android.bundle:1:1178354)
at invokeCallbackAndReturnFlushedQueue (address at index.android.bundle:1:1178297)
```

**Comment by thecodrr** [comment]
Hey, thank you for creating this bug report. This bug has been confirmed & is being tracked here: #785
